# --- First database schema

# --- !Ups

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  id                  int(11)       NOT NULL AUTO_INCREMENT,
  nickname            varchar(100)  NOT NULL DEFAULT '',
  name                varchar(100)  NOT NULL DEFAULT '',
  email               varchar(100)  NOT NULL DEFAULT '',
  avatar              varchar(100)  NOT NULL DEFAULT '',
  application_token   varchar(100)  NOT NULL DEFAULT '', -- token generated by ideas
  token_expiration    timestamp     NOT NULL DEFAULT current_timestamp,
  created             timestamp     NOT NULL DEFAULT current_timestamp,

  PRIMARY KEY (id),
  UNIQUE KEY user_uk_nickname (nickname),
  UNIQUE KEY user_uk_name (name),
  UNIQUE KEY user_uk_email (email)
);

CREATE INDEX user_ix_application_token ON user(application_token);

# --- !Downs

DROP TABLE IF EXISTS `user`;